## numpy array and basics 
learn about 

In [1]:
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
%matplotlib inline


In [3]:
arr_id = np.array([1,2,3,4,5])
print(arr_id)

arr_id2 = np.array([[1,2,3],[4,5,6]])
print(arr_id2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
